import { PotholePost } from '@/types';

export const INITIAL_POSTS: PotholePost[] = [
  {
    id: 'post-1',
    author: {
      name: 'Ravi Kumar',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80',
      handle: '@ravi_kasba',
    },
    location: {
      name: 'Kasba Bus Stand, Main Rd',
      pin: '854330',
      distance: '0.1 km away',
      verified: true,
      lat: 25.8452,
      lng: 87.5341,
    },
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1080&q=80',
    memeCaption: 'कस्बा बस स्टैंड के सामने स्विमिंग पूल मुफ़्त मुफ़्त मुफ़्त! 🏊‍♂️ नगर पालिका ज़िंदाबाद!',
    memeSubtext: 'गहराई इतनी है कि मंगल ग्रह का रोवर भी डूब जाए! 🚀',
    severity: 'CRITICAL',
    metrics: {
      depthCm: 24,
      areaSqM: 1.8,
      count: 4,
    },
    upvotes: 342,
    downvotes: 12,
    commentCount: 45,
    createdAt: '10 min ago',
    tags: ['KasbaStand', 'SwimmingPool', 'CriticalRoad'],
    comments: [
      { id: 'c1', user: 'Amit_Kasba', text: 'कल मेरी बाइक इसमें पूरी गायब हो गई थी 😂', time: '5m ago' },
      { id: 'c2', user: 'Priya_S', text: 'PWD मंत्री जी को टैग करो यार!', time: '2m ago' },
    ],
  },
  {
    id: 'post-2',
    author: {
      name: 'Sneha Singh',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
      handle: '@sneha_purnea',
    },
    location: {
      name: 'Kasba NH-131A Flyover',
      pin: '854330',
      distance: '0.4 km away',
      verified: true,
      lat: 25.8480,
      lng: 87.5310,
    },
    imageUrl: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=1080&q=80',
    memeCaption: 'कस्बा NH-131A रोड: यहाँ गाड़ी कम और चंद्रयान ज़्यादा उछलता है! 🌕🚀',
    memeSubtext: 'नासा वाले यहाँ आकर सस्पेंशन टेस्ट करते हैं!',
    severity: 'HIGH',
    metrics: {
      depthCm: 18,
      areaSqM: 1.2,
      count: 2,
    },
    upvotes: 218,
    downvotes: 5,
    commentCount: 29,
    createdAt: '42 min ago',
    tags: ['NH131A', 'ChandrayaanMode', 'ShockAbsorberKiller'],
    comments: [
      { id: 'c3', user: 'Vikram_Rider', text: 'कमर का डॉक्टर कसबा में ही क्लिनिक खोल ले तो करोड़पति बन जाएगा!', time: '25m ago' },
    ],
  },
  {
    id: 'post-3',
    author: {
      name: 'Mohd Faiz',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&h=120&q=80',
      handle: '@faiz_kasba_854330',
    },
    location: {
      name: 'Kasba Market Road, Ward 4',
      pin: '854330',
      distance: '0.6 km away',
      verified: true,
      lat: 25.8431,
      lng: 87.5388,
    },
    imageUrl: 'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=1080&q=80',
    memeCaption: 'इस गड्ढे की गहराई मापने के लिए ISRO से विशेष वैज्ञानिकों की टीम बुलाई जा रही है! 🔬🔍',
    memeSubtext: 'स्थानीय बच्चों ने इसमें बत्तख पालने की योजना बनाई है। 🦆',
    severity: 'CRITICAL',
    metrics: {
      depthCm: 31,
      areaSqM: 2.4,
      count: 5,
    },
    upvotes: 512,
    downvotes: 18,
    commentCount: 88,
    createdAt: '2 hrs ago',
    tags: ['KasbaBazaar', 'ISRO_Required', 'CivicFail'],
    comments: [
      { id: 'c4', user: 'ChaiWala_Kasba', text: 'कल विधायक जी का काफिला भी इसी में फंसा था भाई!', time: '1h ago' },
      { id: 'c5', user: 'Rajesh_K', text: 'वोट मांगने आएँगे तो यही स्विमिंग पूल दिखाएंगे!', time: '30m ago' },
    ],
  },
  {
    id: 'post-4',
    author: {
      name: 'Puja Kumari',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&h=120&q=80',
      handle: '@puja_kasba',
    },
    location: {
      name: 'Kasba Railway Station Crossing',
      pin: '854330',
      distance: '0.8 km away',
      verified: true,
      lat: 25.8410,
      lng: 87.5395,
    },
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=1080&q=80',
    memeCaption: 'कस्बा स्टेशन रोड: यहाँ सड़क में गड्ढे नहीं, गड्ढों में थोड़ा सा सड़क बचा है! 🕳️🚙',
    memeSubtext: 'दुनिया का 8वाँ अजूबा: बिना बोट के वॉटर राइड का आनंद लें!',
    severity: 'HIGH',
    metrics: {
      depthCm: 15,
      areaSqM: 0.9,
      count: 3,
    },
    upvotes: 189,
    downvotes: 4,
    commentCount: 14,
    createdAt: '4 hrs ago',
    tags: ['StationRoad', 'KasbaStation', 'RollerCoaster'],
    comments: [],
  },
];
